"""Génère les specs AsyncAPI 3.0"""
import yaml
from datetime import datetime
from typing import Dict, Any, List
from loguru import logger
import config

class AsyncAPIGenerator:
    """Génère des spécifications AsyncAPI 3.0"""
    
    @staticmethod
    def generate_spec(
        topic_name: str,
        topic_config: Dict[str, Any],
        schemas: List[Dict[str, Any]],
        message_examples: Dict[str, Any]
    ) -> str:
        """Génère une spec AsyncAPI complète"""
        
        # Structure de base AsyncAPI 3.0
        spec = {
            "asyncapi": "3.0.0",
            "info": {
                "title": f"{topic_name} API",
                "version": "1.0.0",
                "description": f"AsyncAPI specification for Kafka topic '{topic_name}'",
                "contact": {
                    "name": "Generated by Agent AsyncAPI",
                    "email": "marc.verchiani@devoteam.com"
                }
            },
            "servers": {
                "dev": {
                    "host": config.KAFKA_BOOTSTRAP_SERVERS,
                    "protocol": "kafka",
                    "description": "Confluent Cloud Kafka cluster",
                    "security": [
                        {
                            "$ref": "#/components/securitySchemes/saslScram"
                        }
                    ]
                }
            },
            "channels": {},
            "operations": {},
            "components": {
                "messages": {},
                "schemas": {},
                "securitySchemes": {
                    "saslScram": {
                        "type": "scramSha256",
                        "description": "SASL/SCRAM-SHA-256 authentication"
                    }
                }
            }
        }
        
        # Ajouter le channel (topic)
        channel_name = topic_name.replace(".", "_").replace("-", "_")
        spec["channels"][channel_name] = {
            "address": topic_name,
            "messages": {},
            "description": f"Kafka topic for {topic_name}",
            "bindings": {
                "kafka": {
                    "topic": topic_name,
                    "partitions": topic_config.get("partitions", 3),
                    "replicas": topic_config.get("replication_factor", 3)
                }
            }
        }
        
        # Ajouter les messages depuis les schemas
        for schema in schemas:
            message_name = schema["subject"].replace("-", "_")
            
            # Référence au message dans le channel
            spec["channels"][channel_name]["messages"][message_name] = {
                "$ref": f"#/components/messages/{message_name}"
            }
            
            # Définition du message dans components
            spec["components"]["messages"][message_name] = {
                "name": message_name,
                "title": schema["subject"],
                "summary": f"Message schema for {schema['subject']}",
                "contentType": "application/json",
                "payload": {
                    "$ref": f"#/components/schemas/{message_name}_payload"
                }
            }
            
            # Ajouter le schema (converti depuis Avro)
            from tools.schema_analyzer import SchemaAnalyzer
            
            asyncapi_schema = SchemaAnalyzer.avro_to_asyncapi_schema(schema["schema"])
            spec["components"]["schemas"][f"{message_name}_payload"] = asyncapi_schema
            
            # Ajouter un exemple si disponible
            if message_examples:
                spec["components"]["messages"][message_name]["examples"] = [
                    {
                        "name": "example",
                        "summary": "Example message",
                        "payload": message_examples
                    }
                ]
        
        # Ajouter les operations (publish/subscribe)
        spec["operations"]["publishToTopic"] = {
            "action": "send",
            "channel": {"$ref": f"#/channels/{channel_name}"},
            "summary": f"Publish messages to {topic_name}",
            "description": "Operation to publish messages to this Kafka topic"
        }
        
        spec["operations"]["subscribeFromTopic"] = {
            "action": "receive",
            "channel": {"$ref": f"#/channels/{channel_name}"},
            "summary": f"Subscribe to messages from {topic_name}",
            "description": "Operation to consume messages from this Kafka topic"
        }
        
        # Convertir en YAML
        yaml_spec = yaml.dump(spec, default_flow_style=False, sort_keys=False)
        
        return yaml_spec
    
    @staticmethod
    def save_spec(spec_yaml: str, topic_name: str) -> str:
        """Sauvegarde la spec dans un fichier"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{topic_name}_{timestamp}.yaml"
        filepath = config.OUTPUT_DIR / filename
        
        with open(filepath, "w") as f:
            f.write(spec_yaml)
        
        logger.info(f"✓ Spec sauvegardée: {filepath}")
        return str(filepath)